### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by marta-sd** [pknut/IBB#1]
https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L5

I don't like `import *`. How many functions are there? I think you should either list all the functions or use `import chembl_webresource_client as chembl` and then `chembl.TargetResource()` etc

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L8-L9

It's  PDB ID, not PDBbind ID (although PDBbind uses it)

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L11-L16
 
It would be safer to use context manager here:
```python
    with requests.get('http://www.rcsb.org/pdb/rest/describeMol?structureId=%s'
                      % pdbbind_id) as req:
        req_tree = etree.XML(req.text)
        uniprot_id = req_tree.find('.//accession').get('id')
```

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L22

You create new `TargetResource()` for each ID. Why don't we create it globally and reuse? The same applies to `CompoundResource()`.

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L37-L38

You don't need to explain what SMILES is, but you should point out that these ids are **compound** IDs

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L44

What kind of exception we expect here? Be as precise as possible, now it's a great place to miss a bug.

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L52

Add more information to this docstring. First, it prepares data for a given **target**. Second, user needs to know what `smiles` argument does. And you should change the name of this argument, it can be more self-explanatory + you overwrite this variable later (so confusing!)

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L68-L78

You repeat a code with a lot of hard-coded names etc, it would be hard to maintain. I think it should be structured like this:
```python
<create common part of a DataFrame>
column_order = ['chembl id', 'bioactivity type', 'operator', 'value', 'units']    # if you really need it
if smiles:
    data['smiles'] = smiles
    column_order.insert(1, 'smiles')    # again, if you need the order
return data[column_order]    # or just return data
``` 

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L80-L81

This function name is misleading - it also creates a data frame. Also it definitely requires better docstring.

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L85

Oh no, don't do stuff like that without telling the user. Add information to the docstring and issue a warning or something. Also, I think that this should be controlled by an argument with default value (something like `overwrite=False`), maybe someone wants to overwrite an existing file?

https://github.com/pknut/IBB/blob/1a51a96f4e3ea9df6881e47b05cf1d2c48d4c095/ChEMBL.py#L93

This function needs better name, docstring and variable names. Also, it's pandas, why do we loop over indices? There must be a better way

**Comment by pknut** [comment]
Done 0699b1e6beb2a3eacd221632268cb469ea8f0dae

**Comment by marta-sd** [comment]
Looks nice, there are some minor issues:

https://github.com/pknut/IBB/blob/0699b1e6beb2a3eacd221632268cb469ea8f0dae/ChEMBL.py#L46-L50

It's not what I meant, we still don't know which type of error occurred. We want to catch only those cases, in which SMILES were actually unspecified and throw all other exceptions (e.g. when the user specified incorrect ID).  I was thinking about something like:
```python
    for chembl_id in chembl_ids:
        try:
            smiles.append(compounds.get(chembl_id)['smiles'])
        except KeyError as e:
            smiles.append('Unspecified')
```
Now, if the user give us an ID that doesn't exist, this code will throw an exception.

https://github.com/pknut/IBB/blob/0699b1e6beb2a3eacd221632268cb469ea8f0dae/ChEMBL.py#L71-L72

I think we should return an empty DataFrame (with all columns) here. It would make list comprehensions etc easier, e.g.:
```python
all_data = pd.concat([chembl_to_data_frame(unid) for unid in my_ids])
```

https://github.com/pknut/IBB/blob/0699b1e6beb2a3eacd221632268cb469ea8f0dae/ChEMBL.py#L116

It's a little redundant, you can safely change this line to
```python
if overwrite or not os.path.isfile(f):
```

**Comment by pknut** [comment]
Done c4fca02e8a9d997ea25fd744efa198b1c2e01b6a
